export const ERROR_CODES = {
  ALBUM_NOT_FOUND: "ALBUM_NOT_FOUND",
  SONG_NOT_FOUND: "SONG_NOT_FOUND",
  YOUTUBE_API_ERROR: "YOUTUBE_API_ERROR",
  INVALID_PLAYLIST: "INVALID_PLAYLIST",
  EMPTY_PLAYLIST: "EMPTY_PLAYLIST",
  PLAYLIST_NOT_FOUND: "PLAYLIST_NOT_FOUND",
  EMAIL_NOT_FOUND: "EMAIL_NOT_FOUND",
  DAILY_GAME_NOT_FOUND: "DAILY_GAME_NOT_FOUND",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  SESSION_NOT_FOUND: "SESSION_NOT_FOUND",
  GAME_ALREADY_FINISHED: "GAME_ALREADY_FINISHED",
  TRACK_NOT_FOUND: "TRACK_NOT_FOUND",
  GUEST_MISMATCH: "GUEST_MISMATCH",
  USER_MISMATCH: "USER_MISMATCH",
  PLAYER_NOT_FOUND: "PLAYER_NOT_FOUND",
} as const

export type AppErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]
